# Generated by Django 6.0.4 on 2026-05-01 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Tixora Production', 'Scott Staging'", max_length=100, unique=True)),
                ('source_system', models.CharField(help_text="Must match Payment.source_system (e.g. 'tixora', 'scott')", max_length=50, unique=True)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=30, help_text='Max payment initiations per minute')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_logs', to='authentication.apiclient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='authenticat_client__cc3371_idx')],
            },
        ),
    ]
